apiVersion: v1
kind: Service
metadata:
  name: {{ '{{ include "k8s.name" . }}' }}-service
  labels:
    app: {{ '{{ include "k8s.name" . }}' }}
spec:
  type: {{ '{{ .Values.service.type }}' }}
  ports:
    - port: {{ '{{ .Values.service.port }}' }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ '{{ include "k8s.name" . }}' }}
